title: My Home Page
author: Mickhail
email: misha@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  This is my home page. Very nice!

# social links
twitter_username: misha # DO NOT include the @ character, or else the build will fail!
github_username:  elena # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
